% 校准: 从实测速度反推阻力系数
% 策略: 用 max 速度作为全推力稳态目标, 同时用 relaxed-steady 验证
clear; clc;
project_root = setup_paths();

T_data = readtable('data/raw/debug_data260530-1.csv');
dt = mean(diff(T_data.pc_timestamp - T_data.pc_timestamp(1)));

u = T_data.linear_vel_x; v = T_data.linear_vel_y;
w = T_data.linear_vel_z; r = T_data.angular_vel_z;
N = length(u);

du = [0; diff(u)]/dt; dv = [0; diff(v)]/dt;
dw = [0; diff(w)]/dt; dr = [0; diff(r)]/dt;

% 放松的稳态 + 高速段
ss_u_loose = abs(du) < 0.08 & abs(u) > 0.05;
ss_v_loose = abs(dv) < 0.05 & abs(v) > 0.02;
ss_w_loose = abs(dw) < 0.05 & abs(w) > 0.02;
ss_r_loose = abs(dr) < 5.0  & abs(r) > 2;

fprintf('=== 速度分布 (全数据 vs 放松稳态) ===\n');
fprintf('Surge: max=%.2f, P95=%.2f, P50=%.3f | 稳态max=%.2f, 稳态P95=%.2f m/s\n', ...
    max(u), prctile(u,95), median(u), max(u(ss_u_loose)), prctile(u(ss_u_loose),95));
fprintf('Sway:  max=%.3f, P95=%.3f, P50=%.3f | 稳态max=%.3f, 稳态P95=%.3f m/s\n', ...
    max(abs(v)), prctile(abs(v),95), median(abs(v)), ...
    max(abs(v(ss_v_loose))), prctile(abs(v(ss_v_loose)),95));
fprintf('Heave: max=%.3f, P95=%.3f, P50=%.3f | 稳态max=%.3f, 稳态P95=%.3f m/s\n', ...
    max(abs(w)), prctile(abs(w),95), median(abs(w)), ...
    max(abs(w(ss_w_loose))), prctile(abs(w(ss_w_loose)),95));
fprintf('Yaw:   max=%.1f, P95=%.1f, P50=%.1f | 稳态max=%.1f, 稳态P95=%.1f deg/s\n', ...
    max(abs(r)), prctile(abs(r),95), median(abs(r)), ...
    max(abs(r(ss_r_loose))), prctile(abs(r(ss_r_loose)),95));

%% 分析高速段: 最高10%速度的加速度分布
fprintf('\n=== 高速段分析 (top 10%% speed) ===\n');
mask_hi_u = u > prctile(u, 90);
mask_hi_v = abs(v) > prctile(abs(v), 90);
mask_hi_w = abs(w) > prctile(abs(w), 90);
mask_hi_r = abs(r) > prctile(abs(r), 90);

fprintf('Surge 高速 (u>%.2f): |du/dt|: P50=%.3f, P90=%.3f m/s²\n', ...
    prctile(u,90), median(abs(du(mask_hi_u))), prctile(abs(du(mask_hi_u)),90));
fprintf('Sway 高速 (|v|>%.3f): |dv/dt|: P50=%.3f, P90=%.3f m/s²\n', ...
    prctile(abs(v),90), median(abs(dv(mask_hi_v))), prctile(abs(dv(mask_hi_v)),90));
fprintf('Heave高速 (|w|>%.3f): |dw/dt|: P50=%.3f, P90=%.3f m/s²\n', ...
    prctile(abs(w),90), median(abs(dw(mask_hi_w))), prctile(abs(dw(mask_hi_w)),90));
fprintf('Yaw 高速 (|r|>%.0f): |dr/dt|: P50=%.1f, P90=%.1f deg/s²\n', ...
    prctile(abs(r),90), median(abs(dr(mask_hi_r))), prctile(abs(dr(mask_hi_r)),90));

%% 校准: 使用代表性最大速度
rho = 1026;
T_surge = thrust_main(2500, rho);       % 58.78 N
T_aux   = 2 * thrust_aux(2500, rho);    % 10.15 N (双推)
N_yaw   = thrust_aux(2500, rho) * (0.424 + 0.376); % 4.06 N·m
B_excess = 33 * 9.81 * 0.01;            % 1%正浮力 ≈ 3.24 N向上

% Surge: 用全数据max (水平方向,无浮力偏置)
u_max = max(u);

% Sway: 用放松稳态max (全数据max 0.55明显为瞬态)
v_max = max(abs(v(ss_v_loose)));

% Heave: 用放松稳态max, 且扣除浮力偏置
w_max = max(abs(w(ss_w_loose)));
T_heave_net = T_aux - B_excess;  % 净向下推力 = 推力 - 浮力

% Yaw: 用全数据max
r_max = max(abs(r)) * pi/180;

fprintf('\n=== 校准速度目标 ===\n');
fprintf('Surge: u*=%.2f m/s (全数据max)\n', u_max);
fprintf('Sway:  v*=%.3f m/s (放松稳态max, 全数据max=0.55为瞬态)\n', v_max);
fprintf('Heave: w*=%.3f m/s (放松稳态max), 净推力=%.2f-%.2f=%.2f N\n', ...
    w_max, T_aux, B_excess, T_heave_net);
fprintf('Yaw:   r*=%.1f deg/s (全数据max)\n', rad2deg(r_max));

d1_x = 0.76;
d2_x_new = (T_surge - d1_x*u_max) / u_max^2;
fprintf('\nSurge: T=%.1fN → u=%.2f m/s → d1=%.2f, d2=%.1f (原3.8, ×%.1f)\n', ...
    T_surge, u_max, d1_x, d2_x_new, d2_x_new/3.77);

d2_y_new = T_aux / v_max^2;
fprintf('Sway:  T=%.1fN → v=%.3f m/s → d2=%.1f (原142.8, ×%.2f)\n', ...
    T_aux, v_max, d2_y_new, d2_y_new/142.85);

d1_z = 1.45;
d2_z_new = (T_heave_net - d1_z*w_max) / w_max^2;
fprintf('Heave: Tnet=%.1fN → w=%.3f m/s → d1=%.2f, d2=%.1f (原45.0, ×%.1f)\n', ...
    T_heave_net, w_max, d1_z, d2_z_new, d2_z_new/45.04);

dr_new = N_yaw / r_max;
fprintf('Yaw:   N=%.1fNm → r=%.1f deg/s → dr=%.1f (原1.8, ×%.1f)\n', ...
    N_yaw, rad2deg(r_max), dr_new, dr_new/1.849);

%% 写入xhy_drag_cfd.m
fid = fopen(fullfile(project_root, 'src', 'matlab', 'model', 'xhy_drag_cfd.m'), 'w');
fprintf(fid, ['function [tau_drag, D] = xhy_drag_cfd(nu_r, M)\n' ...
    '%% XHY_DRAG_CFD 基于CFD仿真结果的阻力计算（已用实测数据校准）\n' ...
    '%%   校准数据: debug_data260530-1.csv (2026-05-30)\n' ...
    '%%   方法: thrust(2500RPM) = drag(v_max_observed)\n' ...
    '%%\n' ...
    'u = nu_r(1); v = nu_r(2); w = nu_r(3);\n' ...
    'p = nu_r(4); q = nu_r(5); r = nu_r(6);\n' ...
    '\n' ...
    '%% 平动阻力 — CFD形状 + 实测幅值校准\n' ...
    '%% Surge: 实测 v_max=%.2f m/s, 原CFD d2=3.8, 校准×%.1f\n' ...
    'Fx = -(%.4f * u + %.4f * u * abs(u));\n' ...
    '%% Sway:  实测 v_max=%.3f m/s, 原CFD d2=142.8, 校准×%.2f\n' ...
    'Fy = -(%.1f * v + %.1f * v * abs(v));\n' ...
    '%% Heave: 实测 w_max=%.3f m/s, 原CFD d2=45.0, 校准×%.1f\n' ...
    'Fz = -(%.4f * w + %.4f * w * abs(w));\n' ...
    '\n' ...
    '%% 转动阻尼\n' ...
    'zeta4 = 0.3;\n' ...
    'zeta5 = 0.8;\n' ...
    'W = 33 * 9.81;\n' ...
    'r_bg_z = 0;\n' ...
    'r_bb_z = -0.03;\n' ...
    'w4 = sqrt(W * (r_bg_z - r_bb_z) / M(4,4));\n' ...
    'w5 = sqrt(W * (r_bg_z - r_bb_z) / M(5,5));\n' ...
    'T6 = 1;\n' ...
    '\n' ...
    'K  = -M(4,4) * 2 * zeta4 * w4 * p;\n' ...
    'My = -M(5,5) * 2 * zeta5 * w5 * q;\n' ...
    '%% Yaw: 实测 r_max=%.1f deg/s, 原 dr=1.85, 校准×%.1f\n' ...
    'Nz = -M(6,6) / T6 * r * %.2f;\n' ...
    '\n' ...
    'tau_drag = [Fx; Fy; Fz; K; My; Nz];\n' ...
    '\n' ...
    'D = diag([\n' ...
    '    %.4f + %.4f * abs(u);\n' ...
    '    %.1f + %.1f * abs(v);\n' ...
    '    %.4f + %.4f * abs(w);\n' ...
    '    M(4,4) * 2 * zeta4 * w4;\n' ...
    '    M(5,5) * 2 * zeta5 * w5;\n' ...
    '    M(6,6) / T6 * %.2f\n' ...
    '    ]);\n' ...
    'end\n'], ...
    u_max, d2_x_new/3.77, d1_x, d2_x_new, ...
    v_max, d2_y_new/142.85, 0.0, d2_y_new, ...
    w_max, d2_z_new/45.04, d1_z, d2_z_new, ...
    rad2deg(r_max), dr_new/1.849, dr_new/1.849, ...
    d1_x, d2_x_new, 0.0, d2_y_new, d1_z, d2_z_new, dr_new/1.849);
fclose(fid);
fprintf('\n已写入 src/matlab/model/xhy_drag_cfd.m\n');

%% 验证
fprintf('\n--- 仿真验证 (@2500RPM 全推力) ---\n');
Vc = 0; betaVc = 0; w_c = 0; h = 0.05; T_sim = 200;

% Surge
x = zeros(12,1);
for t = 0:h:T_sim, x = x + h * xhy(x, [2500 0 0 0 0]', Vc, betaVc, w_c); end
fprintf('Surge: u=%.2f m/s  (实测max=%.2f, ratio=%.2f)\n', x(1), u_max, x(1)/u_max);

% Sway
x = zeros(12,1);
for t = 0:h:T_sim, x = x + h * xhy(x, [0 0 0 2500 2500]', Vc, betaVc, w_c); end
fprintf('Sway:  v=%.3f m/s (实测max=%.3f, ratio=%.2f)\n', x(2), v_max, x(2)/v_max);

% Heave
x = zeros(12,1);
for t = 0:h:T_sim, x = x + h * xhy(x, [0 2500 2500 0 0]', Vc, betaVc, w_c); end
fprintf('Heave: w=%.3f m/s (实测max=%.3f, ratio=%.2f)\n', x(3), w_max, x(3)/w_max);

% Yaw
x = zeros(12,1);
for t = 0:h:T_sim, x = x + h * xhy(x, [0 0 0 2500 -2500]', Vc, betaVc, w_c); end
fprintf('Yaw:   r=%.0f deg/s (实测max=%.0f, ratio=%.2f)\n', rad2deg(x(6)), rad2deg(r_max), rad2deg(x(6))/rad2deg(r_max));

fprintf('\n校准完成! 所有通道ratio应接近1.0\n');
